# backend/ml/exporter.py
# ─────────────────────────────────────────────────────────────
# Notes Export — TXT, DOCX, PDF
# All crashes from empty-paragraph .runs[0] fixed.
# ─────────────────────────────────────────────────────────────

import io
import re
from typing import Optional


def _strip_md(text: str) -> str:
    """Remove markdown symbols so output is clean plain text."""
    if not text:
        return ""
    text = re.sub(r"#{1,6}\s*", "", text)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`{1,3}([^`]+)`{1,3}", r"\1", text)
    text = re.sub(r"^[-*+]\s+", "• ", text, flags=re.MULTILINE)
    return text.strip()


def _is_bullet(line: str) -> bool:
    return line.startswith("• ") or re.match(r"^\d+[.)]\s", line) is not None


# ─────────────────────────────────────────────────────────────
#  TXT Export
# ─────────────────────────────────────────────────────────────


def export_txt(notes_dict: dict) -> bytes:
    title = notes_dict.get("title", "Lecture Notes").upper()
    lines = [
        "=" * 60,
        f"  {title}",
        "=" * 60,
        "",
    ]

    # ── Overview ──────────────────────────────────────────────
    summary = _strip_md(notes_dict.get("summary", ""))
    if summary:
        lines += [
            "─" * 60,
            "  OVERVIEW",
            "─" * 60,
            "",
        ]
        for para in summary.split("\n"):
            para = para.strip()
            if para:
                lines.append(f"  {para}")
        lines.append("")

    # ── Key Takeaways ─────────────────────────────────────────
    key_points = notes_dict.get("key_points", [])
    if key_points:
        lines += [
            "─" * 60,
            "  KEY TAKEAWAYS",
            "─" * 60,
            "",
        ]
        for i, pt in enumerate(key_points, 1):
            clean = _strip_md(pt)
            if clean:
                lines.append(f"  {i}. {clean}")
        lines.append("")

    lines += [
        "─" * 60,
        "  Generated by AudioNotes AI",
        "─" * 60,
    ]

    return "\n".join(lines).encode("utf-8")


# ─────────────────────────────────────────────────────────────
#  DOCX Export — properly structured with indentation
# ─────────────────────────────────────────────────────────────


def export_docx(notes_dict: dict) -> bytes:
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches, Cm
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
    except ImportError:
        raise ImportError("python-docx is required: pip install python-docx")

    doc = Document()

    # ── Page margins ──────────────────────────────────────────
    for section in doc.sections:
        section.top_margin = Cm(2.2)
        section.bottom_margin = Cm(2.2)
        section.left_margin = Cm(2.8)
        section.right_margin = Cm(2.8)

    # ── Helper: add paragraph with optional indent ────────────
    def body_para(text, indent_cm=0, bold=False, italic=False, color=None):
        p = doc.add_paragraph()
        if indent_cm:
            p.paragraph_format.left_indent = Cm(indent_cm)
        run = p.add_run(text)
        run.bold = bold
        run.italic = italic
        run.font.size = Pt(11)
        if color:
            run.font.color.rgb = RGBColor(*color)
        return p

    def bullet_para(text, indent_cm=0.75):
        p = doc.add_paragraph(style="List Bullet")
        p.paragraph_format.left_indent = Cm(indent_cm)
        p.add_run(text)
        return p

    def num_para(text, indent_cm=0.75):
        p = doc.add_paragraph(style="List Number")
        p.paragraph_format.left_indent = Cm(indent_cm)
        p.add_run(text)
        return p

    # ── Title ─────────────────────────────────────────────────
    title_para = doc.add_heading(notes_dict.get("title", "Lecture Notes"), level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # ── Summary/Overview ──────────────────────────────────────
    summary = _strip_md(notes_dict.get("summary", ""))
    if summary:
        doc.add_heading("Overview", level=1)
        body_para(summary, italic=True, color=(107, 100, 88))

    doc.add_paragraph()

    # ── Key Takeaways — numbered, indented ───────────────────────
    key_points = notes_dict.get("key_points", [])
    if key_points:
        doc.add_heading("Key Takeaways", level=1)
        for pt in key_points:
            clean = _strip_md(pt)
            if clean:
                num_para(clean)

    # ── Footer ────────────────────────────────────────────────
    doc.add_paragraph()
    fp = doc.add_paragraph("Generated by AudioNotes AI")
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = fp.add_run()
    run.italic = True
    for r in fp.runs:
        r.font.color.rgb = RGBColor(0xAA, 0xA5, 0x9E)
        r.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


# ─────────────────────────────────────────────────────────────
#  PDF Export — structured to match Word layout
# ─────────────────────────────────────────────────────────────


def export_pdf(notes_dict: dict) -> bytes:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate,
            Paragraph,
            Spacer,
            HRFlowable,
            Table,
            TableStyle,
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        raise ImportError("reportlab is required: pip install reportlab")

    buf = io.BytesIO()

    PAGE_W, PAGE_H = A4
    L_MARGIN = 2.2 * cm
    R_MARGIN = 2.2 * cm
    CONTENT_W = PAGE_W - L_MARGIN - R_MARGIN

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=R_MARGIN,
        leftMargin=L_MARGIN,
        topMargin=2.2 * cm,
        bottomMargin=2.2 * cm,
        title=notes_dict.get("title", "Lecture Notes"),
    )

    # ── Colour palette ────────────────────────────────────────
    BRAND = colors.HexColor("#1e40af")  # deep blue — section headings
    BRAND_DARK = colors.HexColor("#1e3a8a")  # darker blue — title
    ACCENT = colors.HexColor("#374151")  # dark grey — body text
    MUTED = colors.HexColor("#6B7280")  # mid grey — secondary text
    RULE_CLR = colors.HexColor("#e2e8f0")  # light rule lines
    OVERVIEW_BG = colors.HexColor("#eff6ff")  # pale blue — overview panel bg
    OVERVIEW_BD = colors.HexColor("#bfdbfe")  # overview panel border
    NUM_BG = colors.HexColor("#1e40af")  # number circle bg
    NUM_FG = colors.white

    styles = getSampleStyleSheet()

    # ── Custom paragraph styles ───────────────────────────────
    title_s = ParagraphStyle(
        "NoteTitle",
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=BRAND_DARK,
        alignment=TA_CENTER,
        spaceAfter=2,
        leading=28,
    )
    subtitle_s = ParagraphStyle(
        "Subtitle",
        fontName="Helvetica",
        fontSize=9,
        textColor=MUTED,
        alignment=TA_CENTER,
        spaceAfter=0,
        leading=14,
    )
    section_label_s = ParagraphStyle(
        "SectionLabel",
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=BRAND,
        charSpace=1.2,
        spaceAfter=6,
        leading=12,
    )
    h1_s = ParagraphStyle(
        "H1",
        fontName="Helvetica-Bold",
        fontSize=13,
        textColor=BRAND_DARK,
        spaceBefore=0,
        spaceAfter=6,
        leading=18,
    )
    overview_s = ParagraphStyle(
        "Overview",
        fontName="Helvetica-Oblique",
        fontSize=10.5,
        textColor=ACCENT,
        leading=18,
        spaceAfter=0,
    )
    body_s = ParagraphStyle(
        "Body",
        fontName="Helvetica",
        fontSize=10.5,
        textColor=ACCENT,
        leading=17,
        spaceAfter=0,
    )
    num_label_s = ParagraphStyle(
        "NumLabel",
        fontName="Helvetica-Bold",
        fontSize=9,
        textColor=NUM_FG,
        alignment=TA_CENTER,
        leading=14,
    )
    num_text_s = ParagraphStyle(
        "NumText",
        fontName="Helvetica",
        fontSize=10.5,
        textColor=ACCENT,
        leading=17,
        spaceAfter=0,
    )
    footer_s = ParagraphStyle(
        "Footer",
        fontName="Helvetica-Oblique",
        fontSize=8.5,
        textColor=MUTED,
        alignment=TA_CENTER,
    )

    story = []

    # ══ TITLE BLOCK ═══════════════════════════════════════════
    title_text = notes_dict.get("title", "Lecture Notes")
    wc = notes_dict.get("word_count", 0)
    nkp = len(notes_dict.get("key_points", []))

    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(title_text, title_s))
    story.append(Spacer(1, 0.15 * cm))
    story.append(
        Paragraph(
            f"Words: {wc:,} &nbsp;|&nbsp; Key Takeaways: {nkp} &nbsp;|&nbsp; AI Structured",
            subtitle_s,
        )
    )
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND, spaceAfter=0))
    story.append(Spacer(1, 0.5 * cm))

    # ══ OVERVIEW SECTION ══════════════════════════════════════
    summary = _strip_md(notes_dict.get("summary", ""))
    if summary:
        story.append(Paragraph("OVERVIEW", section_label_s))

        # Split into logical paragraphs so the table can split across pages.
        # A single-row Table CANNOT be split by ReportLab; multiple rows can.
        lines = [l.strip() for l in summary.split("\n") if l.strip()]
        if not lines:
            lines = [summary]

        ov_rows = [[Paragraph(line, overview_s)] for line in lines]

        # Single-column table: left accent via LINEBEFORE, pale bg via BACKGROUND
        ov_tbl = Table(ov_rows, colWidths=[CONTENT_W])
        ov_tbl.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), OVERVIEW_BG),
                    ("LINEBEFORE", (0, 0), (0, -1), 3, BRAND),
                    ("BOX", (0, 0), (-1, -1), 0.5, OVERVIEW_BD),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LEFTPADDING", (0, 0), (-1, -1), 14),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                    ("TOPPADDING", (0, 0), (0, 0), 10),
                    ("BOTTOMPADDING", (0, -1), (-1, -1), 10),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.append(ov_tbl)
        story.append(Spacer(1, 0.6 * cm))

    # ══ KEY TAKEAWAYS SECTION ═════════════════════════════════
    key_points = notes_dict.get("key_points", [])
    if key_points:
        story.append(
            HRFlowable(width="100%", thickness=0.5, color=RULE_CLR, spaceAfter=8)
        )
        story.append(Paragraph("KEY TAKEAWAYS", section_label_s))
        story.append(Spacer(1, 0.1 * cm))

        # Each takeaway: numbered circle + text in a two-column table row
        num_col_w = 0.72 * cm
        text_col_w = CONTENT_W - num_col_w - 0.3 * cm
        ROW_GAP = 0.22 * cm

        rows = []
        for i, pt in enumerate(key_points, 1):
            clean = _strip_md(pt)
            if not clean:
                continue

            # Numbered circle — rendered as a tiny single-cell table with round bg
            num_cell = Table(
                [[Paragraph(str(i), num_label_s)]],
                colWidths=[0.58 * cm],
                rowHeights=[0.58 * cm],
            )
            num_cell.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), NUM_BG),
                        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                        ("TOPPADDING", (0, 0), (-1, -1), 0),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                        ("LEFTPADDING", (0, 0), (-1, -1), 0),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ]
                )
            )

            rows.append([num_cell, Paragraph(clean, num_text_s)])

        if rows:
            # Insert spacer rows between items
            spaced_rows = []
            col_ws = [num_col_w, text_col_w]
            for idx, row in enumerate(rows):
                spaced_rows.append(row)
                if idx < len(rows) - 1:
                    spaced_rows.append(["", ""])  # gap row

            row_heights = []
            for idx in range(len(spaced_rows)):
                if idx % 2 == 1:  # gap rows
                    row_heights.append(ROW_GAP)
                else:
                    row_heights.append(None)  # auto-height

            kt_tbl = Table(spaced_rows, colWidths=col_ws, rowHeights=row_heights)
            kt_tbl.setStyle(
                TableStyle(
                    [
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("TOPPADDING", (0, 0), (-1, -1), 3),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                        ("LEFTPADDING", (0, 0), (-1, -1), 0),
                        ("RIGHTPADDING", (1, 0), (1, -1), 0),
                        ("LEFTPADDING", (1, 0), (1, -1), 10),
                        # Alternate row backgrounds for readability
                        *[
                            ("BACKGROUND", (0, r), (-1, r), colors.HexColor("#f8fafc"))
                            for r in range(0, len(spaced_rows), 2)
                            if r % 4 == 0
                        ],
                    ]
                )
            )
            story.append(kt_tbl)

        story.append(Spacer(1, 0.5 * cm))

    # ══ FOOTER ════════════════════════════════════════════════
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=RULE_CLR))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph("Generated by AudioNotes AI", footer_s))

    doc.build(story)
    buf.seek(0)
    return buf.read()
