# backend/ml/exporter.py
# ─────────────────────────────────────────────────────────────
# Notes Export — TXT, DOCX, PDF
# ─────────────────────────────────────────────────────────────

import io
from typing import Optional


# ─────────────────────────────────────────────────────────────
#  TXT Export
# ─────────────────────────────────────────────────────────────

def export_txt(notes_dict: dict) -> bytes:
    """Return UTF-8 encoded plain text of the notes."""
    from ml.note_structurer import NoteStructurer
    text = NoteStructurer.to_plain_text(notes_dict)
    return text.encode("utf-8")


# ─────────────────────────────────────────────────────────────
#  DOCX Export (python-docx)
# ─────────────────────────────────────────────────────────────

def export_docx(notes_dict: dict) -> bytes:
    """
    Generates a formatted Word document (.docx) from the structured notes.
    Returns bytes.
    """
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise ImportError("python-docx is required: pip install python-docx")

    doc = Document()

    # ── Document title ────────────────────────────────────────
    title_para = doc.add_heading(notes_dict.get("title", "Lecture Notes"), level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # ── Subtitle / summary ────────────────────────────────────
    subtitle = doc.add_paragraph(notes_dict.get("summary", ""))
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].italic = True
    subtitle.runs[0].font.color.rgb = RGBColor(0x6B, 0x64, 0x58)

    doc.add_paragraph()   # spacer

    # ── Stats ─────────────────────────────────────────────────
    stats_para = doc.add_paragraph()
    stats_para.add_run(f"Words transcribed: ").bold = True
    stats_para.add_run(str(notes_dict.get("word_count", 0)))
    stats_para.add_run(f"   |   Sections: ").bold = True
    stats_para.add_run(str(len(notes_dict.get("sections", []))))

    doc.add_paragraph()

    # ── Key Points ────────────────────────────────────────────
    doc.add_heading("Key Points", level=1)
    for i, pt in enumerate(notes_dict.get("key_points", []), 1):
        p = doc.add_paragraph(style="List Number")
        p.add_run(pt)

    doc.add_paragraph()

    # ── Detailed Sections ─────────────────────────────────────
    if notes_dict.get("sections"):
        doc.add_heading("Detailed Notes", level=1)
        for sec in notes_dict["sections"]:
            doc.add_heading(sec["heading"], level=2)
            doc.add_paragraph(sec["content"])

    doc.add_paragraph()

    # ── Full Transcript ───────────────────────────────────────
    doc.add_heading("Full Transcript (English)", level=1)
    transcript_para = doc.add_paragraph(notes_dict.get("full_transcript", ""))
    transcript_para.runs[0].font.size = Pt(10)
    transcript_para.runs[0].font.color.rgb = RGBColor(0x6B, 0x64, 0x58)

    # ── Footer watermark ─────────────────────────────────────
    doc.add_paragraph()
    footer_para = doc.add_paragraph("Generated by AudioNotes AI")
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_para.runs[0].italic = True
    footer_para.runs[0].font.color.rgb = RGBColor(0xAA, 0xA5, 0x9E)

    # ── Serialize to bytes ────────────────────────────────────
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


# ─────────────────────────────────────────────────────────────
#  PDF Export (reportlab)
# ─────────────────────────────────────────────────────────────

def export_pdf(notes_dict: dict) -> bytes:
    """
    Generates a clean PDF from the structured notes.
    Returns bytes.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
            ListFlowable, ListItem,
        )
    except ImportError:
        raise ImportError("reportlab is required: pip install reportlab")

    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title=notes_dict.get("title", "Lecture Notes"),
    )

    styles = getSampleStyleSheet()

    # Custom styles matching Claude theme
    BRAND  = colors.HexColor("#D97706")
    TEXT   = colors.HexColor("#2D2B26")
    MUTED  = colors.HexColor("#6B6458")
    BORDER = colors.HexColor("#E5E2D9")

    title_style = ParagraphStyle(
        "NoteTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=TEXT,
        spaceAfter=6,
    )
    h1_style = ParagraphStyle(
        "H1",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=BRAND,
        spaceBefore=14,
        spaceAfter=6,
        borderPad=0,
    )
    h2_style = ParagraphStyle(
        "H2",
        parent=styles["Heading2"],
        fontName="Helvetica-BoldOblique",
        fontSize=12,
        textColor=TEXT,
        spaceBefore=10,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=TEXT,
        leading=16,
        spaceAfter=6,
    )
    sub_style = ParagraphStyle(
        "Sub",
        parent=body_style,
        textColor=MUTED,
        fontSize=10,
        fontName="Helvetica-Oblique",
    )
    small_style = ParagraphStyle(
        "Small",
        parent=body_style,
        fontSize=9,
        textColor=MUTED,
    )

    story = []

    # Title
    story.append(Paragraph(notes_dict.get("title", "Lecture Notes"), title_style))
    story.append(Paragraph(notes_dict.get("summary", ""), sub_style))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=1.5, color=BRAND))
    story.append(Spacer(1, 0.3 * cm))

    # Stats
    wc   = notes_dict.get("word_count", 0)
    nsec = len(notes_dict.get("sections", []))
    story.append(Paragraph(
        f"<b>Words transcribed:</b> {wc} &nbsp;&nbsp; <b>Sections:</b> {nsec}",
        body_style
    ))
    story.append(Spacer(1, 0.4 * cm))

    # Key Points
    key_points = notes_dict.get("key_points", [])
    if key_points:
        story.append(Paragraph("Key Points", h1_style))
        items = [
            ListItem(Paragraph(pt, body_style), bulletColor=BRAND)
            for pt in key_points
        ]
        story.append(ListFlowable(items, bulletType="bullet", leftIndent=16))
        story.append(Spacer(1, 0.4 * cm))

    # Sections
    sections = notes_dict.get("sections", [])
    if sections:
        story.append(Paragraph("Detailed Notes", h1_style))
        for sec in sections:
            story.append(Paragraph(sec["heading"], h2_style))
            story.append(Paragraph(sec["content"], body_style))
        story.append(Spacer(1, 0.4 * cm))

    # Full Transcript
    full_tr = notes_dict.get("full_transcript", "")
    if full_tr:
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph("Full Transcript (English)", h1_style))
        # Split transcript into paragraphs to avoid overflow
        for chunk in [full_tr[i:i + 800] for i in range(0, len(full_tr), 800)]:
            story.append(Paragraph(chunk, small_style))

    # Footer
    story.append(Spacer(1, 0.6 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Paragraph(
        "Generated by AudioNotes AI — audio-to-notes-ai.vercel.app",
        ParagraphStyle("footer", parent=small_style, alignment=1)
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()
